[package]
name = "opengl-macroquad"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.35.0"
glutin = "0.32.0"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"
rayon = "1.10.0"
winit = "0.30.5"
